
import React,{useState}from"react";
import{createRoot}from"react-dom/client";
import{Home,GraduationCap,LineChart,BookOpen,Bot,Newspaper,CalendarDays,Trophy,Settings,Bell,Search,CheckCircle2,Download,Heart,ThumbsUp,ExternalLink,Plus,Trash2,Upload,ChevronLeft,ChevronRight,Calculator,User,Database,Award,Map,Brain,Target,Lock,LogIn,CreditCard,Menu,X}from"lucide-react";
import{courses}from"./data/courses";
import{quizLevels}from"./data/quizzes";
import{scenarios}from"./data/scenarios";
import"./styles/main.css";
import abLogo from "./assets/ab-smart-trader-logo.jpeg";

type Page="home"|"academy"|"roadmap"|"review"|"simulator"|"journal"|"calculators"|"ai"|"news"|"calendar"|"quiz"|"certificates"|"account"|"progress"|"subscribe";
type AuthUser={name:string;email:string;password:string;paid:boolean;createdAt:string;paymentStatus?:"none"|"pending"|"active"};
const OWNER_EMAIL="ahmadabdeen3720@gmail.com";
const MONTHLY_PRICE=100;
const FREE_LESSONS_LIMIT=3;
type Trade={symbol:string;result:string;pnl:number;capital:number;note:string;date:string;week:string};

const nav=[
["home","الرئيسية",<Home/>],
["academy","الأكاديمية",<GraduationCap/>],
["roadmap","خريطة التعلم",<Map/>],
["review","مراجعة سريعة",<Brain/>],
["progress","تقدم الطالب",<Database/>],
["simulator","المحاكاة",<LineChart/>],
["journal","دفتر التداول PRO",<BookOpen/>],
["calculators","الحاسبات",<Calculator/>],
["ai","تحليل الشارت",<Bot/>],
["news","الأخبار",<Newspaper/>],
["calendar","التقويم",<CalendarDays/>],
["quiz","الاختبارات",<Trophy/>],
["certificates","الشهادات",<Award/>],
["account","الحساب",<User/>]
] as const;

function App(){
 const[page,setPage]=useState<Page>("home");
 const[notice,setNotice]=useState("");
 const[settingsOpen,setSettingsOpen]=useState(false);
 const[searchTerm,setSearchTerm]=useState("");
 const[largeText,setLargeText]=useState(false);
 const[courseId,setCourseId]=useState(courses[0].id);
 const[lessonIndex,setLessonIndex]=useState(0);
 const[user,setUser]=useState<AuthUser|null>(()=>JSON.parse(localStorage.getItem("ab_current_user")||"null"));
 const course=courses.find(c=>c.id===courseId)||courses[0];
 const lesson=course.lessons[lessonIndex]||course.lessons[0];
 const total=courses.reduce((s,c)=>s+c.lessons.length,0);
 const paid=user?.email===OWNER_EMAIL||!!user?.paid||user?.paymentStatus==="active";
 const lockedPages:Page[]=["roadmap","review","progress","simulator","journal","calculators","ai","news","calendar","quiz","certificates"];
 const changePage=(id:Page)=>{if(lockedPages.includes(id)&&!paid){setPage("subscribe");return} setPage(id)};
 if(!user)return <AuthGate setUser={setUser}/>;
 return <div className={largeText?"app appClean sideLayout largeText":"app appClean sideLayout"}><aside className="fixedSide"><div className="brand"><img className="brandLogoImage" src={abLogo} alt="AB Smart Trader"/><div><b>AB Smart Trader</b><span>{paid?"مشترك فعال":"تجربة مجانية - أول 3 دروس"}</span></div></div><div className="sideTools"><button onClick={()=>setNotice(notice?"":"راجع الأخبار قبل التداول، لا تدخل بدون وقف خسارة، وسجل كل صفقة في دفتر التداول.")}><Bell/> تنبيه</button><button onClick={()=>setSettingsOpen(!settingsOpen)}><Settings/> إعدادات</button></div><nav>{nav.map(([id,l,ic])=><button className={page===id?"active":""} onClick={()=>changePage(id as Page)} key={id}>{ic}<span>{l}</span>{lockedPages.includes(id as Page)&&!paid?<Lock className="miniLock"/>:null}</button>)}<button className={page==="subscribe"?"active":""} onClick={()=>setPage("subscribe")}><CreditCard/><span>الاشتراك</span></button></nav></aside><main className="content"><div className="statusLine"><div><b>{user.name}</b><span>{user.email}</span></div><b>{paid?"وصول كامل":"تجربة مجانية"}</b></div>{notice&&<Notice text={notice}/>} {settingsOpen&&<SettingsPanel largeText={largeText} setLargeText={setLargeText}/>} {page==="home"&&<HomePage total={total} setPage={setPage} paid={paid}/>} {page==="academy"&&<Academy course={course} lesson={lesson} lessonIndex={lessonIndex} setLessonIndex={setLessonIndex} setCourseId={setCourseId} paid={paid} setPage={setPage}/>} {page==="subscribe"&&<Subscribe user={user} setUser={setUser}/>} {page==="roadmap"&&<Roadmap/>} {page==="review"&&<QuickReview/>} {page==="progress"&&<Progress total={total}/>} {page==="simulator"&&<Simulator/>}{page==="journal"&&<Journal/>}{page==="calculators"&&<Calculators/>}{page==="ai"&&<Analyzer/>}{page==="news"&&<News/>}{page==="calendar"&&<Calendar/>}{page==="quiz"&&<Quiz/>}{page==="certificates"&&<Certificates/>}{page==="account"&&<Account user={user} setUser={setUser}/>}</main></div>
}

function getUsers():AuthUser[]{return JSON.parse(localStorage.getItem("ab_users")||"[]")}
function saveUsers(users:AuthUser[]){localStorage.setItem("ab_users",JSON.stringify(users))}
function AuthGate({setUser}:any){
 const[mode,setMode]=useState<"login"|"signup">("signup");
 const[name,setName]=useState(""),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[error,setError]=useState("");
 function submit(e:React.FormEvent){e.preventDefault();setError("");const cleanEmail=email.trim().toLowerCase();if(!cleanEmail||password.length<6){setError("اكتب إيميل صحيح وكلمة سر 6 أحرف على الأقل");return}const users=getUsers();if(mode==="signup"){if(!name.trim()){setError("اكتب اسمك");return}if(users.some(u=>u.email===cleanEmail)){setError("هذا الإيميل مسجل مسبقاً، ادخل من تسجيل الدخول");return}const u:AuthUser={name:name.trim(),email:cleanEmail,password,paid:cleanEmail===OWNER_EMAIL,paymentStatus:cleanEmail===OWNER_EMAIL?"active":"none",createdAt:new Date().toISOString()};saveUsers([...users,u]);localStorage.setItem("ab_current_user",JSON.stringify(u));setUser(u);return}const u=users.find(x=>x.email===cleanEmail&&x.password===password);if(!u){setError("الإيميل أو كلمة السر غير صحيحة");return}localStorage.setItem("ab_current_user",JSON.stringify(u));setUser(u)}
 return <main className="authPage"><section className="authCard"><div className="brand authBrand"><img className="authLogoImage" src={abLogo} alt="AB Smart Trader"/><div><b>AB Smart Trader</b><span>أكاديمية تداول باشتراك شهري</span></div></div><h1>{mode==="signup"?"إنشاء حساب جديد":"تسجيل الدخول"}</h1><p>الموقع مقفول. أنشئ حسابك أولاً، جرّب أول {FREE_LESSONS_LIMIT} دروس مجاناً، وبعدها اشترك شهرياً لفتح كل الأكاديمية.</p><form onSubmit={submit}>{mode==="signup"&&<input placeholder="الاسم الكامل" value={name} onChange={e=>setName(e.target.value)}/>}<input placeholder="الإيميل" value={email} onChange={e=>setEmail(e.target.value)}/><input placeholder="كلمة السر" type="password" value={password} onChange={e=>setPassword(e.target.value)}/>{error&&<div className="authError">{error}</div>}<button><LogIn/> {mode==="signup"?"إنشاء الحساب والدخول":"دخول"}</button></form><button className="ghost" onClick={()=>setMode(mode==="signup"?"login":"signup")}>{mode==="signup"?"عندي حساب بالفعل":"إنشاء حساب جديد"}</button><div className="risk">تنبيه: المحتوى تعليمي فقط وليس توصيات مالية ولا يضمن أرباح.</div></section></main>
}

function Subscribe({user,setUser}:any){
 const[proof,setProof]=useState("");
 function sendRequest(){const users=getUsers().map(u=>u.email===user.email?{...u,paymentStatus:"pending" as const}:u);saveUsers(users);const updated:AuthUser={...user,paymentStatus:"pending"};localStorage.setItem("ab_current_user",JSON.stringify(updated));setUser(updated)}
 return <section className="panel subscribe"><h1>الاشتراك الشهري</h1><p>أول {FREE_LESSONS_LIMIT} دروس مجانية. لفتح كل الدروس، الاختبارات، المحاكاة، الشهادات، والذكاء التحليلي اشترك شهرياً.</p><div className="priceBox"><span>الخطة الشهرية</span><b>{MONTHLY_PRICE} شيكل / شهر</b><p>الدفع يكون بتحويل بنكي مباشر لحسابك. بعد التحويل يرسل الطالب رقم العملية أو صورة إثبات الدفع، وبعدها يتم تفعيل حسابه.</p><div className="bankBox"><h3>بيانات التحويل البنكي</h3><p>اسم المستفيد: Ahmad Abdeen</p><p>البنك: ضع اسم البنك هنا</p><p>رقم الحساب / IBAN: ضع رقم حسابك هنا</p><p>المبلغ: {MONTHLY_PRICE} شيكل</p></div><textarea value={proof} onChange={e=>setProof(e.target.value)} placeholder="اكتب رقم عملية التحويل أو ملاحظة الدفع هنا"/><button onClick={sendRequest}><CreditCard/> أرسلت التحويل وأنتظر التفعيل</button><small>عدّل بيانات البنك من ملف src/main.tsx قبل النشر.</small></div>{user.paymentStatus==="pending"&&<div className="notice"><b>طلبك قيد المراجعة</b><p>بعد التأكد من التحويل، يتم تفعيل الحساب من لوحة حساب المالك.</p></div>}</section>
}

function HomePage({total,setPage,paid}:any){
 const done=Object.keys(JSON.parse(localStorage.getItem("v16_progress")||"{}")).length;
 return <section className="home"><div className="hero"><div><div className="heroLogoWrap"><img src={abLogo} alt="AB Smart Trader"/></div><span>Ultimate Trading Academy</span><h1>V16: أكاديمية كاملة للتعلم والتدريب</h1><p>تضم محتوى موسع، ICT Advanced، SMC Mastery، محاكي V2، دفتر تداول PRO، اختبارات كبيرة، مستويات، شهادات، وخريطة تعلم.</p><button onClick={()=>setPage("academy")}>ابدأ الدروس المجانية</button>{!paid&&<button className="secondaryHero" onClick={()=>setPage("subscribe")}>اشترك وافتح كل الأكاديمية</button>}</div><CandleChart type="trendUp"/></div><div className="risk"><b>تنبيه مهم:</b> هذه الأكاديمية تعليمية فقط وليست توصيات مالية ولا تضمن الأرباح. التداول عالي المخاطر وقد يؤدي لخسارة رأس المال.</div><div className="cards"><StatCard n={courses.length} t="مسارات"/><StatCard n={total} t="درس"/><StatCard n={done} t="منجز"/><StatCard n="300+" t="أسئلة"/></div><div className="grid"><Info title="محتوى موسع" text="تمت مضاعفة الأكاديمية إلى مئات الدروس المنظمة."/><Info title="ICT Advanced" text="Turtle Soup, AMD, Market Maker, SMT, Dealing Arrays."/><Info title="محاكي V2" text="80 سيناريو مع تقييم فوري ونقاط."/><Info title="دفتر PRO" text="Win Rate, Drawdown, Profit Factor, Equity Curve."/></div></section>
}

function Info({title,text}:any){return <div className="info"><h3>{title}</h3><p>{text}</p></div>}

function Academy({course,lesson,lessonIndex,setLessonIndex,setCourseId,paid,setPage}:any){
 const isLocked=!paid&&lessonIndex>=FREE_LESSONS_LIMIT;
 return <div className="academyClean"><section className="courseTabs">{courses.map(c=><button className={c.id===course.id?"on":""} onClick={()=>{setCourseId(c.id);setLessonIndex(0)}} key={c.id}>{c.title}</button>)}</section><section className="lesson"><div className="topLesson"><button onClick={()=>setLessonIndex(Math.max(0,lessonIndex-1))}><ChevronRight/> السابق</button><button onClick={()=>setLessonIndex(Math.min(course.lessons.length-1,lessonIndex+1))}>التالي <ChevronLeft/></button></div>{!paid&&<div className="freeBadge">متاح مجاناً: أول {FREE_LESSONS_LIMIT} دروس فقط</div>}<div className="lessonStrip">{course.lessons.map((l:any,i:number)=><button className={i===lessonIndex?"on":""} onClick={()=>setLessonIndex(i)} key={l.id}>{!paid&&i>=FREE_LESSONS_LIMIT?<Lock/>:<CheckCircle2/>}<span>{i+1}. {l.title}</span></button>)}</div>{isLocked?<LockedLesson setPage={setPage}/>:<><h1>{lessonIndex+1}. {lesson.title}</h1><p className="sub">{course.title} • {course.level}</p><div className="def"><GraduationCap/><div><h3>التعريف</h3><p>{lesson.definition}</p></div></div><div className="simple"><h3>ببساطة</h3><p>{lesson.simple}</p></div><div className="example"><h2>مثال عملي على الشارت</h2><p>{lesson.example}</p><CandleChart type={lesson.chart}/></div><div className="two"><div className="box"><h3>مثال شراء</h3><p>{lesson.buyExample}</p></div><div className="box"><h3>مثال بيع</h3><p>{lesson.sellExample}</p></div></div><div className="risk"><b>لماذا قد تفشل؟</b><p>{lesson.failureExample}</p></div><div className="points"><h2>الخلاصة</h2>{lesson.summary.map((p:string)=><p key={p}><CheckCircle2/> {p}</p>)}</div><div className="actions"><button onClick={()=>downloadLessonSummary(lesson)}><Download/> ملخص</button><button onClick={()=>saveFavorite(lesson.title)}><Heart/> مفضلة</button><button className="done" onClick={()=>saveProgress(course.id, lessonIndex)}><ThumbsUp/> تم الفهم</button></div></>}</section></div>
}
function LockedLesson({setPage}:any){return <div className="lockedLesson"><Lock/><h1>هذا الدرس للمشتركين فقط</h1><p>جرّبت الدروس المجانية. اشترك شهرياً لفتح باقي الأكاديمية بالكامل.</p><button onClick={()=>setPage("subscribe")}><CreditCard/> اشترك الآن</button></div>}


function Notice({text}:{text:string}){return <div className="notice"><b>إشعار مهم</b><p>{text}</p></div>}

function SettingsPanel({largeText,setLargeText}:any){
 return <div className="notice"><b>الإعدادات</b><p>تحكم بسيط بتجربة القراءة داخل الأكاديمية.</p><button onClick={()=>setLargeText(!largeText)}>{largeText?"تصغير الخط":"تكبير الخط"}</button><button onClick={()=>localStorage.clear()}>مسح التخزين المحلي</button></div>
}

function SearchResults({q,setCourseId,setLessonIndex,setPage}:any){
 const term=String(q||"").trim();
 if(!term)return null;
 const results:any[]=[];
 courses.forEach(c=>c.lessons.forEach((l:any,i:number)=>{
  const text=(c.title+" "+l.title+" "+l.definition+" "+l.simple).toLowerCase();
  if(text.includes(term.toLowerCase()))results.push({c,l,i});
 }));
 return <div className="notice"><b>نتائج البحث: {results.length}</b><div className="searchResults">{results.slice(0,8).map(r=><button key={r.c.id+r.i} onClick={()=>{setCourseId(r.c.id);setLessonIndex(r.i);setPage("academy")}}>{r.c.title} - {r.l.title}</button>)}</div></div>
}

function downloadLessonSummary(lesson:any){
 const content=`${lesson.title}\n\n${lesson.definition}\n\nببساطة:\n${lesson.simple}\n\nمثال:\n${lesson.example}\n\nتنبيه: المحتوى تعليمي وليس توصية مالية.`;
 const blob=new Blob([content],{type:"text/plain;charset=utf-8"});
 const a=document.createElement("a");
 a.href=URL.createObjectURL(blob);
 a.download=`${lesson.title}.txt`;
 a.click();
 URL.revokeObjectURL(a.href);
}

function saveFavorite(title:string){
 const key="v16_favorites";
 const arr=JSON.parse(localStorage.getItem(key)||"[]");
 if(!arr.includes(title))arr.push(title);
 localStorage.setItem(key,JSON.stringify(arr));
 alert("تم حفظ الدرس في المفضلة");
}

function saveProgress(courseId:string, lessonIndex:number){const key="v16_progress";const old=JSON.parse(localStorage.getItem(key)||"{}");old[`${courseId}-${lessonIndex}`]=true;localStorage.setItem(key,JSON.stringify(old));alert("تم حفظ تقدمك محليًا")}
function Progress({total}:any){const progress=JSON.parse(localStorage.getItem("v16_progress")||"{}");const done=Object.keys(progress).length;const pct=Math.min(100,Math.round(done/total*100));const level=pct<20?"طالب جديد":pct<40?"مبتدئ":pct<60?"متوسط":pct<80?"متقدم":"محترف";return <section className="panel"><h1>تقدم الطالب والمستويات</h1><div className="cards"><StatCard n={done} t="دروس منتهية"/><StatCard n={total-done} t="دروس متبقية"/><StatCard n={pct+"%"} t="نسبة الإنجاز"/><StatCard n={level} t="مستواك"/></div><div className="progressBar"><span style={{width:pct+"%"}}></span></div><div className="grid"><Info title="نظام XP" text="كل درس تنهيه يرفع مستواك داخل الأكاديمية."/><Info title="الشهادات" text="كل مرحلة لها شهادة داخلية عند إتمامها."/><Info title="الخريطة" text="اتبع المسارات من المبتدئ حتى ICT Advanced."/><Info title="الربط السحابي" text="النسخة جاهزة للربط مع Supabase لاحقًا."/></div></section>}
function Roadmap(){const steps=["المسار المبتدئ","الشموع اليابانية","التحليل الفني","إدارة المخاطر","Price Action","SMC Mastery","ICT Advanced","محاكاة V2","دفتر التداول PRO","الاختبار النهائي"];return <section className="panel"><h1>خريطة التعلم</h1><div className="roadmap">{steps.map((s,i)=><div key={s}><b>{i+1}</b><h3>{s}</h3><p>أنهِ هذه المرحلة قبل الانتقال للمرحلة التالية.</p></div>)}</div></section>}
function QuickReview(){const items=["BOS: كسر هيكل واضح.","CHoCH: تغير أولي في السلوك.","FVG: فراغ سعري يحتاج سياقًا.","Liquidity: سيولة فوق القمم وتحت القيعان.","Risk: لا تدخل بدون وقف وحجم محسوب.","OTE: منطقة تصحيح وليست إشارة وحدها.","Judas Swing: حركة خداع في بداية الجلسة.","Turtle Soup: سحب قمة/قاع ثم انعكاس."];return <section className="panel"><h1>مركز المراجعة السريعة</h1><div className="grid">{items.map(x=><Info key={x} title={x.split(":")[0]} text={x}/>)}</div></section>}
function Candle({x,o,c,h,l}:{x:number,o:number,c:number,h:number,l:number}){const green=c<o;const top=Math.min(o,c),height=Math.max(8,Math.abs(c-o));return <g><line x1={x} y1={h} x2={x} y2={l} stroke={green?"#22c55e":"#ef4444"} strokeWidth="4" strokeLinecap="round"/><rect x={x-9} y={top} width="18" height={height} rx="4" fill={green?"#22c55e":"#ef4444"}/></g>}
function CandleChart({type="trendUp"}:{type?:string}){const patterns:Record<string,number[]>={trendUp:[130,118,126,105,112,92,100,78,86,62,74,52],volatile:[105,135,90,130,75,115,95,145,80,120,70,110],retest:[135,118,105,88,70,58,74,86,82,70,68,54],news:[110,112,108,35,50,95,90,120,115,80,78,98],plan:[140,125,130,105,110,82,88,70,76,55,65,48],structure:[135,120,128,108,112,86,96,72,82,58,70,48],liquidity:[120,110,112,102,106,96,88,52,60,115,108,130],supplyDemand:[70,90,85,105,100,128,122,145,138,112,118,135],fakeBreak:[120,110,105,90,88,70,76,48,62,115,112,128],range:[110,90,95,125,120,92,98,128,124,94,100,120],candleParts:[105,80,120,90,110,85,125,95,100,70,118,88],hammer:[95,120,110,135,125,145,136,118,112,80,92,70],engulfing:[110,125,122,135,130,105,120,86,92,70,80,58],doji:[100,102,104,103,98,99,105,104,96,98,101,100],closePower:[130,110,118,95,104,82,90,68,74,55,64,45],supportResistance:[120,105,112,128,122,106,110,130,125,105,112,95],volume:[125,110,118,100,106,82,95,70,80,60,70,48],doubleBottom:[80,105,112,135,128,100,92,125,116,84,75,55],bos:[130,116,120,98,100,78,82,58,62,42,50,35],choch:[60,45,55,70,68,92,86,112,105,132,125,145],orderBlock:[128,110,116,92,96,70,74,50,58,40,45,35],fvg:[130,112,116,72,78,50,58,38,45,30,42,28],risk:[95,88,100,92,105,96,110,104,115,108,120,112],positionSize:[120,98,108,90,100,82,92,70,88,76,84,74],rr:[140,124,130,110,118,94,102,78,88,62,74,50],stopLoss:[115,100,108,88,96,76,84,102,110,130,126,118],weeklyLoss:[65,78,72,88,82,100,95,112,108,126,120,140]};const arr=patterns[type]||patterns.trendUp;const candles=[];for(let i=0;i<6;i++){const o=arr[i*2],c=arr[i*2+1];candles.push({x:70+i*60,o,c,h:Math.min(o,c)-18,l:Math.max(o,c)+18});}return <svg className="chart" viewBox="0 0 500 190"><rect x="20" y="20" width="460" height="145" rx="14" fill="rgba(255,255,255,.025)" stroke="rgba(255,255,255,.08)"/>{[55,95,135].map(y=><line key={y} x1="35" y1={y} x2="465" y2={y} stroke="rgba(255,255,255,.08)" strokeDasharray="6 8"/>)}{candles.map((c,i)=><Candle key={i} {...c}/>)}{(type==="liquidity"||type==="fakeBreak")&&<line x1="40" y1="55" x2="460" y2="55" stroke="#ef4444" strokeWidth="3" strokeDasharray="10 8"/>}{(type==="supportResistance"||type==="hammer"||type==="range")&&<line x1="40" y1="130" x2="460" y2="130" stroke="#22c55e" strokeWidth="3" strokeDasharray="10 8"/>}{type==="fvg"&&<rect x="160" y="58" width="150" height="32" rx="8" fill="rgba(59,130,246,.22)" stroke="#60a5fa"/>}{type==="orderBlock"&&<rect x="80" y="105" width="70" height="42" rx="8" fill="rgba(34,197,94,.18)" stroke="#22c55e"/>}</svg>}
function Simulator(){const[step,setStep]=useState(0);const[msg,setMsg]=useState("");const[score,setScore]=useState(0);const s=scenarios[step%scenarios.length];const choices=["دخول مباشر","انتظار تأكيد","انتظار إعادة اختبار","إلغاء الصفقة","دخول بعد تأكيد","بيع بعد تأكيد"];return <section className="panel"><h1>المحاكي V2</h1><div className="cards"><StatCard n={step+1} t="سيناريو"/><StatCard n={score} t="نقاطك"/><StatCard n={scenarios.length} t="سيناريو متاح"/><StatCard n="V2" t="تقييم فوري"/></div><h2>{s.title}</h2><p>{s.text}</p><CandleChart type={s.variant}/><div className="choices">{choices.map(x=><button onClick={()=>{const ok=x===s.good;setMsg(ok?s.answer:"راجع قرارك: القرار الأفضل هنا هو "+s.good);if(ok)setScore(v=>v+10)}} key={x}>{x}</button>)}</div>{msg&&<div className="result">{msg}</div>}<button onClick={()=>{setStep(step+1);setMsg("")}}>سيناريو جديد</button></section>}
function getWeek(){const d=new Date();const first=new Date(d.getFullYear(),0,1);const week=Math.ceil((((d.getTime()-first.getTime())/86400000)+first.getDay()+1)/7);return `${d.getFullYear()}-W${week}`}
function Journal(){const[trades,setTrades]=useState<Trade[]>(JSON.parse(localStorage.getItem("tradesV16")||"[]"));const[symbol,setSymbol]=useState("XAUUSD"),[result,setResult]=useState("ربح"),[pnl,setPnl]=useState(25),[capital,setCapital]=useState(1000),[note,setNote]=useState("");function add(){const t={symbol,result,pnl:Number(pnl),capital:Number(capital),note,date:new Date().toLocaleDateString(),week:getWeek()};const arr=[t,...trades];setTrades(arr);localStorage.setItem("tradesV16",JSON.stringify(arr));setNote("")}function del(i:number){const arr=trades.filter((_,x)=>x!==i);setTrades(arr);localStorage.setItem("tradesV16",JSON.stringify(arr))}const weekly=trades.filter(t=>t.week===getWeek());const wins=trades.filter(t=>t.result==="ربح");const losses=trades.filter(t=>t.result==="خسارة");const profit=trades.reduce((s,t)=>s+(t.result==="ربح"?Math.abs(t.pnl):t.result==="خسارة"?-Math.abs(t.pnl):0),0);const winRate=trades.length?Math.round(wins.length/trades.length*100):0;const avgWin=wins.length?wins.reduce((s,t)=>s+Math.abs(t.pnl),0)/wins.length:0;const avgLoss=losses.length?losses.reduce((s,t)=>s+Math.abs(t.pnl),0)/losses.length:0;const profitFactor=avgLoss?((avgWin*wins.length)/(avgLoss*losses.length||1)):0;const drawdown=Math.min(0, profit);return <section className="panel"><h1>دفتر التداول PRO</h1><div className="cards"><StatCard n={trades.length} t="صفقات"/><StatCard n={winRate+"%"} t="Win Rate"/><StatCard n={profit.toFixed(2)} t="صافي الأداء"/><StatCard n={profitFactor.toFixed(2)} t="Profit Factor"/><StatCard n={avgWin.toFixed(2)} t="Average Win"/><StatCard n={avgLoss.toFixed(2)} t="Average Loss"/><StatCard n={drawdown.toFixed(2)} t="Drawdown"/><StatCard n={weekly.length} t="صفقات الأسبوع"/></div><div className="equity"><span style={{width:Math.min(100,Math.max(5,50+profit/10))+"%"}}></span></div><div className="form"><input value={symbol} onChange={e=>setSymbol(e.target.value)}/><select value={result} onChange={e=>setResult(e.target.value)}><option>ربح</option><option>خسارة</option><option>تعادل</option></select><input type="number" value={pnl} onChange={e=>setPnl(+e.target.value)} placeholder="قيمة الربح/الخسارة"/><input type="number" value={capital} onChange={e=>setCapital(+e.target.value)} placeholder="رأس المال"/><input placeholder="ملاحظة" value={note} onChange={e=>setNote(e.target.value)}/><button onClick={add}><Plus/> إضافة صفقة</button></div><div className="table">{trades.map((t,i)=><div key={i}><b>{t.symbol}</b><span>{t.result}</span><span>{t.pnl}</span><p>{t.note}</p><small>{t.date}</small><button onClick={()=>del(i)}><Trash2/></button></div>)}</div></section>}
function Calculators(){const[capital,setCapital]=useState(1000),[risk,setRisk]=useState(1),[entry,setEntry]=useState(100),[sl,setSl]=useState(95),[tp,setTp]=useState(110);const riskMoney=capital*risk/100;const stop=Math.abs(entry-sl);const size=stop?riskMoney/stop:0;const rr=stop?Math.abs(tp-entry)/stop:0;const growth=capital*Math.pow(1+(risk/100),20);return <section className="panel"><h1>حاسبات التداول</h1><div className="form"><input type="number" value={capital} onChange={e=>setCapital(+e.target.value)} placeholder="رأس المال"/><input type="number" value={risk} onChange={e=>setRisk(+e.target.value)} placeholder="المخاطرة %"/><input type="number" value={entry} onChange={e=>setEntry(+e.target.value)} placeholder="الدخول"/><input type="number" value={sl} onChange={e=>setSl(+e.target.value)} placeholder="الوقف"/><input type="number" value={tp} onChange={e=>setTp(+e.target.value)} placeholder="الهدف"/></div><div className="cards"><StatCard n={riskMoney.toFixed(2)} t="قيمة المخاطرة"/><StatCard n={size.toFixed(4)} t="حجم تقريبي"/><StatCard n={"1:"+rr.toFixed(2)} t="Risk/Reward"/><StatCard n={growth.toFixed(2)} t="نمو افتراضي"/></div></section>}
function Analyzer(){const[url,setUrl]=useState("");const[analysis,setAnalysis]=useState("");const[count,setCount]=useState(0);function onFile(e:React.ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];if(!f)return;setUrl(URL.createObjectURL(f));const n=count+1;setCount(n);const size=f.size;let direction=size%3===0?"صاعد":size%3===1?"هابط":"عرضي / غير واضح";setAnalysis(`تحليل تعليمي رقم ${n}: الاتجاه المحتمل ${direction}. افحص الدعم والمقاومة، BOS/CHoCH، السيولة، FVG، ولا تدخل من الصورة فقط بدون خطة وإدارة مخاطر.`);e.target.value=""}return <section className="panel"><h1>تحليل الشارت V2</h1><div className="risk">تنبيه: التحليل تعليمي وليس توصية مالية. التداول قد يؤدي لخسارة رأس المال.</div><label className="upload"><Upload/> اختر صورة شارت<input type="file" accept="image/*" onChange={onFile}/></label>{url&&<img className="preview" src={url}/>} {analysis&&<div className="result">{analysis}</div>}</section>}
function News(){const links=[["TradingView عربي","رسوم وتحليلات وأفكار تداول","https://ar.tradingview.com/"],["TradingView Ideas","أفكار وتحليلات المتداولين","https://ar.tradingview.com/ideas/"],["FXStreet عربي","أخبار وتحليلات فوركس","https://ar.fxstreet.com/"],["FXStreet Calendar","تقويم اقتصادي مباشر","https://ar.fxstreet.com/economic-calendar"]];return <section className="panel"><h1>روابط الأخبار والتحليلات</h1><div className="news">{links.map(l=><div key={l[0]}><h3>{l[0]}</h3><p>{l[1]}</p><button onClick={()=>window.open(l[2],"_blank")}><ExternalLink/> فتح الموقع</button></div>)}</div></section>}
function Calendar(){return <section className="panel"><h1>التقويم الاقتصادي</h1><button className="bigLink" onClick={()=>window.open("https://ar.fxstreet.com/economic-calendar","_blank")}><CalendarDays/> فتح التقويم الاقتصادي FXStreet عربي</button></section>}
function Quiz(){const[level,setLevel]=useState<string>(quizLevels[0].id);const[order,setOrder]=useState<any[]>([...quizLevels[0].questions].sort(()=>Math.random()-0.5));const[idx,setIdx]=useState(0);const[score,setScore]=useState(0);const[done,setDone]=useState(false);const[msg,setMsg]=useState("");function reset(id=level){const lv=quizLevels.find(l=>l.id===id)||quizLevels[0];setLevel(id);setOrder([...lv.questions].sort(()=>Math.random()-0.5));setIdx(0);setScore(0);setDone(false);setMsg("")}const lv=quizLevels.find(l=>l.id===level)||quizLevels[0];const q=order[idx]||lv.questions[0];function answer(i:number){const ok=i===q.answer;setMsg(ok?"صحيح":"خطأ");if(ok)setScore(s=>s+1);setTimeout(()=>{if(idx<order.length-1){setIdx(x=>x+1);setMsg("")}else setDone(true)},450)}return <section className="panel"><h1>اختبارات V2</h1><p>بنك أسئلة كبير: {quizLevels.reduce((s,l)=>s+l.questions.length,0)} سؤال.</p><div className="tabs">{quizLevels.map(l=><button className={l.id===level?"active":""} onClick={()=>reset(l.id)} key={l.id}>{l.title} - {l.difficulty}</button>)}</div>{!done?<div className="quiz"><h3>{q.q}</h3>{q.choices.map((c:any,i:number)=><button onClick={()=>answer(i)} key={c}>{c}</button>)}<p>السؤال {idx+1} من {order.length}</p>{msg&&<div className="result">{msg}</div>}</div>:<div className="result">انتهى الاختبار. نتيجتك: {score} / {order.length}<br/><button onClick={()=>reset()}>إعادة المستوى</button></div>}</section>}
function Certificates(){const progress=JSON.parse(localStorage.getItem("v16_progress")||"{}");const done=Object.keys(progress).length;const certs=["شهادة المبتدئ","شهادة التحليل الفني","شهادة إدارة المخاطر","شهادة SMC","شهادة ICT","الشهادة النهائية"];return <section className="panel"><h1>الشهادات والمستويات</h1><div className="news">{certs.map((c,i)=><div key={c}><Award/><h3>{c}</h3><p>{done>i*20?"متاحة":"مقفلة حتى تنهي المزيد من الدروس"}</p></div>)}</div></section>}
function Account({user,setUser}:any){function logout(){localStorage.removeItem("ab_current_user");setUser(null)}const isOwner=user.email===OWNER_EMAIL;const[users,setUsers]=useState<AuthUser[]>(getUsers());function activate(email:string){const arr=getUsers().map(u=>u.email===email?{...u,paid:true,paymentStatus:"active" as const}:u);saveUsers(arr);setUsers(arr)}return <section className="panel"><h1>حسابي</h1><p>الإيميل: {user.email}</p><p>حالة الاشتراك: <b>{isOwner?"مالك - مفتوح كامل":user.paid||user.paymentStatus==="active"?"فعال":"تجربة مجانية"}</b></p><div className="cards"><StatCard n={isOwner||user.paid?"Active":"Free"} t="الاشتراك"/><StatCard n="Email" t="تسجيل دخول"/><StatCard n="Bank" t="الدفع"/><StatCard n="Locked" t="حماية المحتوى"/></div>{isOwner&&<div className="adminBox"><h2>تفعيل المشتركين</h2><p>هذه اللوحة تظهر فقط لإيميل المالك المجاني: {OWNER_EMAIL}</p>{users.filter(u=>u.email!==OWNER_EMAIL).map(u=><div className="adminUser" key={u.email}><span>{u.name}<br/><small>{u.email}</small></span><b>{u.paid?"فعال":u.paymentStatus==="pending"?"بانتظار الدفع":"مجاني"}</b>{!u.paid&&<button onClick={()=>activate(u.email)}>تفعيل</button>}</div>)}</div>}<button onClick={logout}>تسجيل خروج</button></section>}
function StatCard({n,t}:any){return <div className="card"><b>{n}</b><span>{t}</span></div>}
createRoot(document.getElementById("root")!).render(<App/>);
